memsim: memsim.cpp
	echo     ------------compiling memsim.cpp to create executable program memsim----------------
	g++  -ggdb   -std=c++11   memsim.cpp   -o   memsim

clean:
	echo ----------------removing executable program memsim--------------------
	/bin/rm memsim
